### PR TITLE
Update README.md to reflect new env variable

### PR DESCRIPTION
**Pull request by dmamills**
I've set up a new pub and noticed the readme is slightly out of date with some env variable changes you made. The fix was explained in #8.  It also renames the process to `easy-ssb-pub` which aligns with the docker commands listed above.

Thanks for this project!

### CODE REVIEW

**Comment by staltz** [comment]
Hi @dmamills. That's odd, we renamed from `PUB_URL` to `HOST` so the current readme.md is correct. How did you try to install it? Through `git clone` or `docker pull`?

**Comment by dmamills** [comment]
I had installed it using `docker pull`. It was giving me the error mentioned [here](https://github.com/staltz/easy-ssb-pub/issues/8#issuecomment-293515361) on the invite page.

**Comment by staltz** [comment]
Yeah I think we just need to update the docker image. For now try to use git clone

**Comment by dmamills** [comment]
Will do, thanks for the help. Sorry about trying to send the readme back in time! 😄

**Pull request closed without merging**
